### ISSUE TITLE
Documentation error?

### ISSUE THREAD

**Issue by starfiend** [manwar/data-types#3]
The documentation to is_int appears to be wrong. is_int function itself appears to be correct. is_int(-22) correctly returns true, documentation suggests it should return false
is_whole function and documentation also appear to be incorrect. -1 is a whole (negative) number, but returns false.

**Comment by andresodio** [comment]
When will this be fixed in CPAN? It still says incorrectly that is_int(-22) returns false: [https://metacpan.org/pod/Data::Types](https://metacpan.org/pod/Data::Types)
